Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\takis\OneDrive - The University of Manchester\MSc-Hybrid-IDS\src\sids\test_sids.py", line 37, in <module>
    test_model()
  File "C:\Users\takis\OneDrive - The University of Manchester\MSc-Hybrid-IDS\src\sids\test_sids.py", line 15, in test_model
    feature_names = load_feature_names("src/sids/sids_rules/feature_names.txt")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\takis\OneDrive - The University of Manchester\MSc-Hybrid-IDS\src\sids\test_sids.py", line 8, in load_feature_names
    with open(filepath, "r") as f:
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'src/sids/sids_rules/feature_names.txt'
Loaded 22544 rows and 42 columns.
